import queue
q=queue.PriorityQueue()
q.put(10)
q.put(20)
q.put(70)
q.put(600)
q.put(608)
q.put(607)
q.put(30)
q.put(27)
print(q.get())
print(q.get())
print(q.get())
print(q.get())
print(q.get())

q_t=[]
q_t.append((1,"alex"))
q_t.append((4,"ex"))
q_t.append((10,"x"))
q_t.append((11,"ale"))
q_t.append((32,"aex"))
q_t.sort(reverse=True)
print(q_t)
print(q_t.pop(0))
